### ISSUE TITLE
What is the structure of SQL tables created by this extension?

### ISSUE THREAD

**Issue by QyInvoLing** [clarkwinkelmann/flarum-ext-anonymous-posting#1]
I accidentally clicked on "reset" button in admin panel and after that, every time a user creates new anonymous post/discussion, it occurs an 500 internal server error with the following log:

Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mi.anonymous_user_discussion' doesn't exist (SQL: select count(*) as aggregate from `discussions` inner join `anonymous_user_discussion` on `discussions`.`id` = `anonymous_user_discussion`.`discussion_id` where `anonymous_user_discussion`.`anonymous_user_id` is null)

So, dear author, is there any way of automatically fixing the SQL structure? If not, I would manually fix the SQL after knowing the structure.

Thank you!

**Comment by clarkwinkelmann** [comment]
That's a strange error because there shouldn't be any table with a name like this.

The extension adds a column `anonymous_user_id` to both the `discussions` and `posts` table. Both are `UNSIGNED INT NULLABLE` with an index. The name of the index is auto-generated by Flarum from the table and column name so I'm not sure exactly how it should be named.

I'm not sure what you mean by "Reset" button? The "Purge" button? If you accidentally "purge"/"uninstall"/"roll back" the extension, enabling it again should re-create the 2 columns automatically.

**Comment by QyInvoLing** [comment]
Thank you for your reply! I checked the database again, and i found that there were these two columns in discussions and posts, but it still doesn't works. Maybe flarum does a bit more work I don't know. Once I got it, I'll give out the full solution!

**Comment by clarkwinkelmann** [comment]
While doing other tests I noticed that there can be table not found errors when extensions try to use some of the fake relationships I added to the extension in an unexpected way.

If you still encounter issues, please share your `php flarum info` output and if possible try disabling other extensions to see if it makes any difference.

I'll close this for now but feel free to re-open with more details.

**Comment by QyInvoLing** [comment]
Hello! This time I got a more detailed error given by flarum!
I'm not that familiar with SQL, but I guess that the problem probably comes from the database.

[2022-09-14 14:09:45] flarum.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'anonymous_user_id' in 'field list' in /www/wwwroot/michan/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'anonymous_user_id' in 'field list' in /www/wwwroot/michan/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18



Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'anonymous_user_id' in 'field list' (SQL: insert into `posts` (`is_approved`, `created_at`, `discussion_id`, `user_id`, `type`, `ip_address`, `content`, `anonymous_user_id`, `dice_rolls_20`, `is_private`, `number`) values (1, 2022-09-14 14:09:45, 168, ?, comment, 218.188.148.5, <t><p>test anonymous</p></t>, 1, , 0, (select IFNULL(MAX(pn.number), 0) + 1 from `posts` as `pn` where pn.discussion_id = 168))) in /www/wwwroot/michan/vendor/illuminate/database/Connection.php:712

**Comment by clarkwinkelmann** [comment]
Does the `anonymous_user_id` column exist on your `posts` table? That SQL looks good, that particular column is supposed to exist.

**Comment by QyInvoLing** [comment]
OK, I created these columns and created the database, and do the same thing again.
From the latest log I got the key: it's auto moderator! Auto moderator doesn't allow a reply's user_id = NULL, so the error comes out!
After removing auto moderator, everything works perfectly! THANKS FOR YOUR HELP!!
